name: CODE REVIEW REPORT
on:
  #pull_request:
  #    types: [opened, edited, reopened, synchronize]
  issue_comment:
permissions: read-all
jobs:
  pr_agent_report:
    permissions:
      contents: write
      pull-requests: write
    if: (contains(github.event.comment.body, '/generate_report') && github.event.comment.user.login != 'nex-maximus') ||
        github.event_name == 'pull_request' && github.event.pull_request.user.login != 'nex-maximus'
    runs-on: [self-hosted, genai_copilot-code-review]
    steps:
      - name: PR Agent report action step
        id: report
        run: |
         cd  ../../../genai_pr_agent
         chmod +x ./get_pr_eval_report.sh
         echo runner | sudo -S chmod +777 /home/runner/scripts/.env
         echo runner | sudo cp /home/runner/scripts/.env /home/runner/scripts/.env_copy
         ./get_pr_eval_report.sh
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          USE_CUSTOM_MODEL: true
          CUSTOM_PROD_API_BASE: ${{ secrets.CUSTOM_PROD_API_BASE }}
          CUSTOM_PROD_API_KEY: ${{ secrets.CUSTOM_PROD_API_KEY }}
          GPT4128K_DEPLOY_NAME: ${{ secrets.GPT4128K_DEPLOY_NAME }}
          CUSTOM_API_VERSION: ${{ secrets.CUSTOM_API_VERSION }}
          CUSTOM_PUSH_TOKEN: ${{ secrets.CUSTOM_PUSH_TOKEN }}
